name: Test server
on: 
  push:
    paths:
      - 'server/**'
  workflow_dispatch:

jobs: 
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test server
        working-directory: ./server
        run: | 
          go test ./...
        